# Thanks for using my plugin =D #

Option:
  UpdateNotify: false
  BlockTime: 40
  Signs: false
  UseRaw: false
  RawMsg: '&c&oNem választottál ki effektet!'
  RawSelect: '&b&nKattints ide az effektek menüjéhez'
  NoTrailsPerm: '&eNincs jogod ehhez az effekthez.'
  NoCmdPerm: '&eEhhez nincs jogod.'
  IfTrailsAllow: '&a&lKattints a választáshoz!'
  IfTrailsDisallow: '&c&lNem lehet hozzáférni ehhez az effekthez.'
  Line: '&6------------------'
  Selected: '&6Választott effekted: &7'
  None: None
  Back: '&fVissza a főmenübe'
  BackItemId: 381
  BackItemData: 0
  BackButton: true
  MsgRemove: '&cKikapcsoltad az összes rajtad levő effektet.'
  DisableWhenPlayerDontMoving: false
  TimeToDisable: 15
  KeepMenuOpen: false
  DefaultMenu: Main
  HideInCombat: false
  CombatTimeColdown: 40
  SecoundClickRemove: false
  QuitTrailRemove: false
  HideInVanish: false
  Mode: 0
  CheckPermission: false
  CheckPeriod: 100
  CheckOnJoin: false
  SaveTrails: true
  ModeChanger: false
  ModeChangerItemName: '&6&lMód megváltoztatása'
  ModeChangerSlot: 4
  WingsTrail: true
  HideWingsInMoving: false
  TList: My presents
  ChrismasItem: '&fAjándékaim'
  UnlockedParticle: '&e!Count!/25'
  UnlockedBlocks: '&e!Count!/8'
  UnlockedRains: '&e!Count!/5'
  BlockedWorlds:
  - 12
  InvisHide: false
  EventItem: '&fMy trails'
  BlockChestOpening: false
  Event: false
  EventMenuName: Chest opening...
  WingsMenu: Types
  WingsAnimation: false
  LimitPlayers: 10
  LimitMessage: '&cYou''re unable to select trail'
  LimitTrails: false
  RainFix: false
  RainMinimalTimeAlive: false
  PreventRainFromStuck: false
MySQL:
  Enable: false
  host: localhost
  port: 3306
  database: db
  user: user
  password: password
Signs:
  Line1: '&lKattints a megnyitáshoz!'
  Line2: '&lEffekt menü'
  Line3: '&8&n!T!'
  Line4: ''
Sounds:
  Enable: false
  Particles: CAT_MEOW
  Blocks: DIG_GRAVEL
  Rains: FIZZ
  Remove: NOTE_PLING
JoinItem:
  Enable: false
  Id: 377
  Data: 0
  Name: '&6Effektek'
  Slot: 8
  LeftClick: false
  RightClick: true
MultipleTrails:
  Enable: false
  AddedMsg: '&aHozzáadott effekt: &7'
  Limit: 5
  VipLimit: 10
  AllR: '&cMinden effekt törölve lett.'
  LMsg: '&cElérted a maximum választható effektek számát.'
  UMsg: '&cEzt az effektet már használod.'
  BMsg: '&cNem használhatsz egynél több blokk effektet.'
  RMsg: '&cNem használhatsz egynél több eső effektet.'
Extra:
  ParticleItem: '&6&lRészecske Effektek'
  BlockItem: '&2&lBlokk Effektek'
  RainItem: '&3&lEső Effektek'
  BetaItem: '&7&lBéta Effektek'
  WingsItem: '&7&lSzárny Készítő'
  RemItem: '&c&lEffektek Eltüntetése'
  ChooseTypeMenu: Válassz Típust!
  ParticleMenu: Effektek
  BlockMenu: Blokk Effektek
  RainMenu: Eső Effektek
  List: Ki használ effektet
  White: '&fFehér'
  Red: '&cPiros'
  Yellow: '&eSárga'
  Green: '&aZöld'
  Blue: '&9Kék'
  Purple: '&dLila'
  Black: '&7Fekete'
  RTBpage1: Eső Effekt Késző 1/2
  RTBpage2: Eső Effekt Késző 2/2
  ModeMenu: Kiválasztó mód
  DefaultMode: Alapmód
  CircleMode: Körmód
  NNMode: NN mód
  Wings1: Szín kiválasztása (1/2)
  Wings2: Kontúr kiválasztása (2/2)
  Wings3: Harmadik szín kiválasztása (3/2)
  SkipThird: '&7Kattints ide a harmadik szín kihagyásáért!'
  Wings: Szárny
  Cancel: '&c&lKész'
  BfW: '&ePillangó'
  Wings0: Válaszd ki a szárny típusát
  AngelW: '&fAngyal'
DonationButton:
  Enable: false
  Name: '&a&l!player!'
  Lore:
  - '&fHello'
  ID: 1
  Data: 0
  Message: Az adakozásért kattins ide!
  Link: http://
RainPos:
  TimeToRemove: 1
  X: 0
  Y: 4
  Z: 0
  ItemY: 3
  ItemX: 0
  ItemZ: 0
Heart:
  Display: true
  Name: Szív Effekt
  Item: '&cSzív'
  ITA: ''
  ITD: ''
  S: 9
  Y: 0.5
Angry:
  Display: true
  Name: Mérges Effekt
  Item: '&6Mérges'
  ITA: ''
  ITD: ''
  S: 10
  Y: 0.5
Magic:
  Display: true
  Name: Mágia Effekt
  Item: '&3Mágia'
  Speed: 0
  ITA: ''
  ITD: ''
  S: 11
  Y: 1
Fun:
  Display: true
  Name: Szín Effekt
  Item: '&eSzínek'
  ITA: ''
  ITD: ''
  S: 12
  Y: 0.5
Cloud:
  Display: true
  Name: Felhő Effekt
  Item: '&fFelhő'
  Speed: 0.0
  ITA: ''
  ITD: ''
  S: 13
  Y: 1
Witch:
  Display: true
  Name: Boszorkány Bűbáj Effekt
  Item: '&bBoszorkány Bűbáj'
  Speed: 0.3
  ITA: ''
  ITD: ''
  S: 14
  Y: 0.5
Ender:
  Display: true
  Name: Bevégző Effekt
  Item: '&5Bevégző'
  Speed: 0.5
  ITA: ''
  ITD: ''
  S: 15
  Y: 0.5
Green:
  Display: true
  Name: Zöld Effekt
  Item: '&aZöld'
  ITA: ''
  ITD: ''
  S: 16
  Y: 0.5
Spark:
  Display: true
  Name: Csillámlás Effekt
  Item: '&fCsillámlás'
  Speed: 0.4
  ITA: ''
  ITD: ''
  S: 17
  Y: 0.5
Flame:
  Display: true
  Name: Tűz Effekt
  Item: '&6Tűz'
  Speed: 0
  ITA: ''
  ITD: ''
  S: 18
  Y: 0.5
WhiteMagic:
  Display: true
  Name: Fehér Varázslat Effekt
  Item: '&fFehér Varázslat'
  Speed: 0.3
  ITA: ''
  ITD: ''
  S: 19
  Y: 0.5
Note:
  Display: true
  Name: Zene Effekt
  Item: '&dZene'
  ITA: ''
  ITD: ''
  S: 20
  Y: 0
Snow:
  Display: true
  Name: Hó Effekt
  Item: '&fHó'
  Speed: 0.2
  ITA: ''
  ITD: ''
  S: 21
  Y: 0.5
Water:
  Display: true
  Name: Víz Effekt
  Item: '&bVíz'
  ITA: ''
  ITD: ''
  S: 22
  Y: 0.5
Lava:
  Display: true
  Name: Láva Effekt
  Item: '&6Láva'
  ITA: ''
  ITD: ''
  S: 23
  Y: 0.5
Crit:
  Display: true
  Name: Kritikus Csapás Effekt
  Item: '&6Kritikus Csapás'
  Speed: 0.2
  ITA: ''
  ITD: ''
  S: 24
  Y: 0.5
Smoke:
  Display: true
  Name: Füs Effekt
  Item: '&7Füst'
  Speed: 0.2
  ITA: ''
  ITD: ''
  S: 25
  Y: 0.5
Spell:
  Display: true
  Name: 1-es Bűbáj Effekt
  Item: '&5Bűbáj'
  ITA: ''
  ITD: ''
  S: 26
  Y: 0.5
Enchant:
  Display: true
  Name: Varázslat Effekt
  Item: '&fVarázslat'
  Speed: 0
  ITA: ''
  ITD: ''
  S: 27
  Y: 0.5
Splash:
  Display: true
  Name: Csobbanás Effekt
  Item: '&9Csobbanás'
  ITA: ''
  ITD: ''
  S: 28
  Y: 0.5
Slime:
  Display: true
  Name: Nyálka Effekt
  Item: '&aNyálka'
  ITA: ''
  ITD: ''
  S: 29
  Y: 0.5
Snowball:
  Display: true
  Name: Hógolyó Effekt
  Item: '&fSHógolyó'
  ITA: ''
  ITD: ''
  S: 30
  Y: 0.5
Spell2:
  Name: 2-es Bűbáj Effekt
  Y: 0.5
Red:
  Display: true
  Name: Piros Effekt
  Item: '&4Piros'
  ITA: ''
  ITD: ''
  S: 31
  Y: 0.5
Void:
  Display: true
  Name: Üresség Effekt
  Item: '&7Üresség'
  ITA: ''
  ITD: ''
  S: 31
  Y: 0.5
Pop:
  Display: true
  Name: Pattogás Effekt
  Item: '&ePattogás'
  ITA: ''
  ITD: ''
  S: 32
  Y: 0.5
Rainbow:
  Display: true
  Name: Szivárvány Effekt
  Item: '&6Szivárvány'
  ITA: ''
  ITD: ''
  S: 33
  Y: 0.3
Breath:
  Display: true
  Name: Sárkány Lehellet Effekt
  Item: '&5Sárkány Lehellet'
  ITA: ''
  ITD: ''
  S: 34
  Y: 0.3
EndRod:
  Display: true
  Name: VégRúd Effekt
  Item: '&fVégRúd'
  ITA: ''
  ITD: ''
  S: 35
  Y: 0.3
Damage:
  Display: true
  Name: Sérülés Effekt
  Item: '&4Sérülés'
  ITA: ''
  ITD: ''
  S: 36
  Y: 0
FSand:
  Display: true
  Name: Homok Effekt
  Item: '&eHomok'
  Speed: 0.2
  ITA: ''
  ITD: ''
  S: 37
  Y: 0
Totem:
  Display: true
  Name: Totem Effekt
  Item: '&7Totem'
  Speed: 0.2
  ITA: ''
  ITD: ''
  S: 38
  Y: 0.4
Blocks:
  Name:
    Rainbow: Szivárvány Üveg
    Flower: Virág Blokkok
    Carpet: Szőnyeg Blokkok
    Redstone: Vöröskő Blokkok
    Sea: Tenger Blokkok
    Wheat: Búza Blokkok
    Ore: Érc Blokkok
    Clay: Agyag Blokkok
  Items:
    Rainbow: '&fSzivárvány Üveg'
    Flower: '&cVirág Blokkok'
    Carpet: '&eSzőnyeg Blokkok'
    Redstone: '&aVöröskő Blokkok'
    Sea: '&9Tenger Blokkok'
    Wheat: '&5Búza Blokkok'
    Ore: '&6Érc Blokkok'
    Clay: '&3Agyag Blokkok'
  Slot:
    Rainbow: 11
    Flower: 12
    Carpet: 13
    Redstone: 14
    Sea: 15
    Wheat: 22
    Ore: 21
    Clay: 23
  ITA:
    Rainbow: ''
    Flower: ''
    Carpet: ''
    Redstone: ''
    Sea: ''
    Wheat: ''
    Ore: ''
    Clay: ''
  ITD:
    Rainbow: ''
    Flower: ''
    Carpet: ''
    Redstone: ''
    Sea: ''
    Wheat: ''
    Ore: ''
    Clay: ''
Rains:
  Name:
    Tear: Könny Eső
    Blood: Véreső
    Dia: Gyémánt Eső
    Wart: Bibircsók Eső
    Gold: Arany Eső
    Builder: Egyedi Eső
  Items:
    Tear: '&6Könny Eső'
    Blood: '&4Véreső'
    Dia: '&bGyémánt Eső'
    Wart: '&5Bibircsók Eső'
    Gold: '&6Arany Eső'
    Builder: '&aEső Készítő'
  Slot:
    Tear: 11
    Blood: 12
    Dia: 13
    Wart: 14
    Gold: 15
    Builder: 31
  ITA:
    Tear: ''
    Blood: ''
    Dia: ''
    Wart: ''
    Gold: ''
    Builder: ''
  ITD:
    Tear: ''
    Blood: ''
    Dia: ''
    Wart: ''
    Gold: ''
    Builder: ''
