# ----------------------------------------------------------------------------#
#                                                                             #
#                             Minesweeper config                              #
#                                                                             #
# ----------------------------------------------------------------------------#

# name of the language file (in the folder 'language')
langFile: "lang_hu.yml"

gameBox:
  mainButton:
    # define the Material and data for the button (format: 'material:data')
    materialData: "TNT"
    # display name of the button
    displayName: "&3Aknakereső"
    # lore of the button
    lore:
    - ""
    - "&1Nézi a lépésedet..."
  gameButtons:
    easy:
      materialData: "WOOL:13"
      displayName: "&aKönnyű"
      lore:
      - ""
      - "&1Akna: &r5"
      - "&1Ár: &45"
      - "&1Jutalom: &a7"
      mines: 5
      # When an empty slot is revealed, surrounding slots are revealed automatically
      #   default: true
      automaticRevealing: true
      slot: 20
      cost: 5
      reward: 7
    normal:
      materialData: "WOOL:1"
      displayName: "&6Normal"
      lore:
      - ""
      - "&1Akna: &r8"
      - "&1Ár: &410"
      - "&1Jutalom: &a15"
      mines: 8
      cost: 10
      reward: 15
      slot: 29
    saveStats:
      materialData: "diamond_block"
      displayName: "&c&lVerseny"
      lore:
      - ""
      - "&1Akna: &r13"
      - "&cKerülj fel a &ltop listára"
      - "&aSok Sikert"
      - ""
      - "&1Ára: &450"
      - "&1RJutalom: &a75"
      - "&1Token: &a3"
      mines: 10
      big: false
      slot: 24
      cost: 50
      reward: 75
      # if true the best score of this button is saved
      saveStats: true
      tokens: 3
  topListButtons:
    # use the same key as the game you want to display the top list for
    #   for that button 'saveStats' must be true (see above)
    saveStats:
      materialData: "diamond_block"
      displayName: "&cTop lista"
      lore:
      - ""
      - "&cCompetition &1top list"
      slot: 33
      # inventory title of the top list (%player% and %game%)
      inventoryTitle: '              Top List'
      # Lore of the skulls in the inventory. Use %rank% for the rank and %time% for the time in 'mm:ss'
      skullLore:
      - ''
      - '&6Rank:&1 %rank%'
      - '&6Idő:&1 %time%'


rules:
  # enable/disable sound
  playSounds: true


# requires vault and an economy plugin
#   to enable economy do not forget to enable it for GameBox too
economy:
  enabled: false

# use "Material:data" or "ID:data"
materials:
  cover: "160:7"
  flag: "SIGN"
  mine: "TNT"
  warning: "WOOL:1"

displaynames:
  cover: "&bTakarás"
  warning: "&cFigyelmeztetés"
  mine: "&4Akna"
  flag: "&1Zászló"
