# ----------------------------------------------------------------------------#
#                                                                             #
#                      Rock Paper Scissors config                             #
#                                                                             #
# ----------------------------------------------------------------------------#

# name of the language file (in the folder 'language')
#   the default.yml file is overwritten on every server restart!
#   This means you will have to use the other files to customize the messages, but since i am adding messages regulary in updates
#   you can use the default file if you just want to have the up to date english default messages
langFile: "lang_hu.yml"

gameBox:
  mainButton:
    # define the Material and data for the button (format: 'material:data')
    materialData: "shears"
    # display name of the button
    displayName: "&3Kő-Papír-Olló"
    # lore of the button
    lore:
    - ""
    - "&1Küzdj, mint a profik!"
  gameButtons:
    saveStats:
      materialData: "PAPER"
      displayName: "&l&1Kő-Papír-Olló"
      lore:
      - ""
      - '&1Ára: &45'
      - '&1Nyeremény: &29'
      - ""
      - "&15 körből a legjobb nyer!"
      # slot of the button in the gui
      #   be careful to not use the same twice ;)
      slot: 22
      cost: 5
      reward: 9
      # time in seconds for each turn (default 10)
      timePerTurn: 10
      # time in seconds between turns (default 5)
      waitPerTurn: 5
      inviteGuiTitle: "     &3Kő-Papír-Olló"
      saveStats: true
      # Only use numbers up to 9. Preferably uneven ones to get rid of draws.
      rounds: 5
  topListButtons:
    # use the same key as the game you want to display the top list for
    #   for that button 'saveStats' must be true (see above)
    saveStats:
      materialData: "nether_star"
      displayName: "&l&cToplista"
      lore:
      - ""
      - "&1Kő-Papír-Olló pontszámok"
      slot: 31
      # inventory title of the top list (%player% and %game%)
      inventoryTitle: '              Toplista'
      # Lore of the skulls in the inventory. Use %rank% for the rank and %wins% for the number of wins
      skullLore:
      - ''
      - '&6Helyezés:&1 %rank%'
      - '&6Nyerések száma:&1 %wins%'

scissors:
  materialData: 'shears'
  displayName: '&5Olló'
paper:
  materialData: 'paper'
  displayName: '&5Papír'
rock:
  materialData: 'cobblestone'
  displayName: '&5Kő'

# indicators
indicatorWon:
  materialData: 'stained_glass_pane:5'
  displayName: '&5Nyertél.'
indicatorPlaceholder:
  materialData: 'stained_glass_pane:7'
  displayName: '&5'
