worlds:
  plotworld:
    RoadMainBlock: '1'
    ProtectedWallBlock: '44:4'
    PlotFloorBlock: '2'
    GroundHeight: 64
    UnclaimedBorder: '44:5'
    ForSaleWallBlock: '44'
    PlotSize: 43
    ZTranslation: 0
    RoadAltBlock: '1:6'
    WallBlock: '44:5'
    FillBlock: '3'
    PathWidth: 7
    XTranslation: 0
    AuctionWallBlock: '44'
