# ----------------------------------------------------------------------------#
#                                                                             #
#                              Match It config                                #
#                                                                             #
#                                  by Nikl                                    #
# ----------------------------------------------------------------------------#

# name of the language file (in the folder 'language')
langFile: "lang_hu.yml"

rules:
  # enable/disable sound
  playSounds: true

# requires vault and an economy plugin
#   to enable economy do not forget to enable it for GameBox too
economy:
  enabled: false

gameBox:
  mainButton:
    # define the Material and data for the button (format: 'material:data')
    materialData: "95:11"
    # display name of the button
    displayName: "&3Párkereső"
    # lore of the button
    lore:
    - ""
    - "&1Memória játék."
    - "&1Találd meg az összes párt."
  gameButtons:
    small:
      materialData: "95:11"
      displayName: "&aKis játék"
      lore:
      - ""
      - "Párok: &15"
      slot: 11
      cost: 0
      size: "small"
      # time in seconds until a mismatched pair is covered again (default 1.5)
      timeVisible: 1.5
    medium:
      materialData: "95:11"
      displayName: "&aKözepes játék"
      lore:
      - ""
      - "Párok: &114"
      slot: 20
      cost: 0
      size: "medium"
    big:
      materialData: "95:11"
      displayName: "&aNagy játék"
      lore:
      - ""
      - "Párok: &127"
      - ""
      - "Nézd meg a top listát ;)"
      slot: 29
      cost: 0
      size: "big"
      # if true the best score of this button is saved
      saveStats: true

  topListButtons:
    # use the same key as the game you want to display the top list for
    #   for that button 'saveStats' must be true (see above)
    big:
      materialData: "95:13"
      displayName: "&6Nagy játék &c&lTop lista"
      slot: 24
      # inventory title of the top list (%player% and %game%)
      inventoryTitle: '        &6Párkereső &rTop lista'
      # Lore of the skulls in the inventory. Use %rank% for the rank and %time% for the players' best time
      skullLore:
      - ''
      - '&6Rang:&1 %rank%'
      - '&6Idő:&1 %time%'

coverItem:
  materialData: "160:3"
  displayName: "&1Kattints a felfedezéshez"

borderItem:
  materialData: "160:15"
  displayName: ""

items:
  '1':
    # material data of the item
    materialData: "98"
    # optional custom display name
    displayName: "&1Kőtégla"
    # optional custom lore
    lore:
    - ""
    - "Régi, kevés repedéssel"
  '2':
    # material data of the item
    materialData: "100"
    # optional custom display name
    displayName: "&1Piros gomba block"
  '3':
    # material data of the item
    materialData: "101"
    # optional custom display name
    displayName: "&1Vasrács"
  '4':
    # material data of the item
    materialData: "103"
    # optional custom display name
    displayName: "&1Dinnye"
  '5':
    # material data of the item
    materialData: "106"
    # optional custom display name
    displayName: "&1Inda"
  '6':
    # material data of the item
    materialData: "387"
    # optional custom display name
    displayName: "&1Könyv"
    lore:
    - ""
    - "Olvasd el!"
    - "     - Tanárod"
  '7':
    # material data of the item
    materialData: "diamond"
    # optional custom display name
    displayName: "&1Gyémánt"
  '8':
    # material data of the item
    materialData: "emerald"
    # optional custom display name
    displayName: "&1Smaragd"
  '9':
    # material data of the item
    materialData: "341"
    # optional custom display name
    displayName: "&1Nyálka"
  '10':
    # material data of the item
    materialData: "egg"
    # optional custom display name
    displayName: "&1Tojás"
  '11':
    # material data of the item
    materialData: "302"
    # optional custom display name
    displayName: "&1Ősi sapka"
    lore:
    - ""
    - "Talán Cézár hordta ezt?"
  '12':
    # material data of the item
    materialData: "357"
    # optional custom display name
    displayName: "&1Süti"
    lore:
    - ""
    - "Nagymama sütije a legjobb!"
  '13':
    # material data of the item
    materialData: "352"
    # optional custom display name
    displayName: "&1Csont"
  '14':
    # material data of the item
    materialData: "358"
    # optional custom display name
    displayName: "&1Kincses térkép"
    lore:
    - ""
    - "Kíváncsi vagyok hová vezet..."
  '15':
    materialData: "35:13"
    displayName: "&1Zöld gyapjú"
  '16':
    materialData: "35:14"
    displayName: "&1Piros gyapjú"
  '17':
    materialData: "38"
    displayName: "&1Pipacs"
    lore:
    - ""
    - "Gyönyörű!"
  '18':
    materialData: "40"
    displayName: "&1Piros gomba"
    lore:
    - ""
    - "Ne edd meg!"
  '19':
    materialData: "tnt"
    displayName: "&1TNT"
    lore:
    - ""
    - "TNT vagyok, dinamit vagyok!"
    - "   Nézz, ahogy felrobbanoook!!"
  '20':
    materialData: "jukebox"
    displayName: "&1Zenedoboz"
    lore:
    - ""
    - "Zene a levegőben"
  '21':
    materialData: "dragon_egg"
    displayName: "&1Sárkány tojás"
  '22':
    materialData: "anvil"
    displayName: "&1Üllő"
  '23':
    materialData: "111"
    displayName: "&1Tavirózsa"
  '24':
    materialData: "116"
    displayName: "&1Varázsasztal"
    lore:
    - ""
    - "Ez fekete mágia!"
  '25':
    materialData: "double_plant"
    displayName: "&1Napraforgó"
  '26':
    materialData: "288"
    displayName: "&1Toll"
  '27':
    materialData: "315"
    displayName: "&1Arany mellvért"
    lore:
    - ""
    - "Különleges!"
  '28':
    materialData: "bookshelf"
    displayName: "&1Könyvespolc"
    lore:
    - ""
    - "Olvasd el az összes könyvet, építs egy rakétát"
    - "   és repülj el a holdra ;)"
  '29':
    materialData: "cactus"
    displayName: "&1Kaktusz"
  '30':
    materialData: "170"
    displayName: "&1Szalmabála"
  '31':
    materialData: "267"
    displayName: "&1Kard"
    lore:
    - ""
    - "Egyszerű vaskard."
    - "Unalmas..."


