# ----------------------------------------------------------------------------#
#                                                                             #
#                              Match It config                                #
#                                                                             #
#                                  by Nikl                                    #
# ----------------------------------------------------------------------------#

# name of the language file (in the folder 'language')
langFile: "lang_hu.yml"

rules:
  # enable/disable sound
  playSounds: true

# requires vault and an economy plugin
#   to enable economy do not forget to enable it for GameBox too
economy:
  enabled: false

gameBox:
  mainButton:
    # define the Material and data for the button (format: 'material:data')
    materialData: "stained_glass:11"
    # display name of the button
    displayName: "&3Párkereső"
    # lore of the button
    lore:
    - ""
    - "&1Memóriajáték."
    - "&1Találd meg az összes párt."
  gameButtons:
    small:
      materialData: "stained_glass:11"
      displayName: "&aKis játék"
      lore:
      - ""
      - "Párok: &15"
      slot: 11
      cost: 0
      size: "small"
      # time in seconds until a mismatched pair is covered again (default 1.5)
      timeVisible: 1.5
    medium:
      materialData: "stained_glass:11"
      displayName: "&aKözepes játék"
      lore:
      - ""
      - "Párok: &114"
      slot: 20
      cost: 0
      size: "medium"
    big:
      materialData: "stained_glass:11"
      displayName: "&aNagy játék"
      lore:
      - ""
      - "Párok: &127"
      - ""
      - "Nézd meg a toplistát ;)"
      slot: 29
      cost: 0
      size: "big"
      # if true the best score of this button is saved
      saveStats: true

  topListButtons:
    # use the same key as the game you want to display the top list for
    #   for that button 'saveStats' must be true (see above)
    big:
      materialData: "stained_glass:13"
      displayName: "&6Nagy játék &c&lToplista"
      slot: 24
      # inventory title of the top list (%player% and %game%)
      inventoryTitle: '        &6Párkereső &rToplista'
      # Lore of the skulls in the inventory. Use %rank% for the rank and %time% for the players' best time
      skullLore:
      - ''
      - '&6Helyezés:&1 %rank%'
      - '&6Idő:&1 %time%'

coverItem:
  materialData: "stained_glass_pane:3"
  displayName: "&1Kattints a felfedéshez"

borderItem:
  materialData: "stained_glass_pane:15"
  displayName: ""

items:
  '1':
    # material data of the item
    materialData: "SMOOTH_BRICK:2"
    # optional custom display name
    displayName: "&1Kőtégla"
    # optional custom lore
    lore:
    - ""
    - "Régi, számos repedéssel"
  '2':
    # material data of the item
    materialData: "HUGE_MUSHROOM_2"
    # optional custom display name
    displayName: "&1Piros gombablokk"
  '3':
    # material data of the item
    materialData: "IRON_FENCE"
    # optional custom display name
    displayName: "&1Vasrács"
  '4':
    # material data of the item
    materialData: "melon_block"
    # optional custom display name
    displayName: "&1Dinnye"
  '5':
    # material data of the item
    materialData: "vine"
    # optional custom display name
    displayName: "&1Inda"
  '6':
    # material data of the item
    materialData: "written_book"
    # optional custom display name
    displayName: "&1Könyv"
    lore:
    - ""
    - "Olvasd el!"
    - "     - Tanárod"
  '7':
    # material data of the item
    materialData: "diamond"
    # optional custom display name
    displayName: "&1Gyémánt"
  '8':
    # material data of the item
    materialData: "emerald"
    # optional custom display name
    displayName: "&1Smaragd"
  '9':
    # material data of the item
    materialData: "slime_ball"
    # optional custom display name
    displayName: "&1Nyálka"
  '10':
    # material data of the item
    materialData: "egg"
    # optional custom display name
    displayName: "&1Tojás"
  '11':
    # material data of the item
    materialData: "chainmail_helmet"
    # optional custom display name
    displayName: "&1Ókori sisak"
    lore:
    - ""
    - "Talán Caesear hordta ezt?"
  '12':
    # material data of the item
    materialData: "cookie"
    # optional custom display name
    displayName: "&1Süti"
    lore:
    - ""
    - "Nagyi sütije a legjobb!"
  '13':
    # material data of the item
    materialData: "bone"
    # optional custom display name
    displayName: "&1Csont"
  '14':
    # material data of the item
    materialData: "map"
    # optional custom display name
    displayName: "&1Kincses térkép"
    lore:
    - ""
    - "Kíváncsi vagyok hová vezet..."
  '15':
    materialData: "wool:13"
    displayName: "&1Zöld gyapjú"
  '16':
    materialData: "wool:14"
    displayName: "&1Piros gyapjú"
  '17':
    materialData: "RED_ROSE"
    displayName: "&1Pipacs"
    lore:
    - ""
    - "Gyönyörű!"
  '18':
    materialData: "red_mushroom"
    displayName: "&1Piros gomba"
    lore:
    - ""
    - "Ne edd meg!"
  '19':
    materialData: "tnt"
    displayName: "&1TNT"
    lore:
    - ""
    - "TNT vagyok, dinamit vagyok!"
    - "   Nézd, ahogy felrobbanoook!!"
  '20':
    materialData: "jukebox"
    displayName: "&1Zenedoboz"
    lore:
    - ""
    - "Zene a levegőben..."
  '21':
    materialData: "dragon_egg"
    displayName: "&1Sárkány tojás"
  '22':
    materialData: "anvil"
    displayName: "&1Üllő"
  '23':
    materialData: "WATER_LILY"
    displayName: "&1Tavirózsa"
  '24':
    materialData: "ENCHANTMENT_TABLE"
    displayName: "&1Varázslóasztal"
    lore:
    - ""
    - "Ez fekete mágia!"
  '25':
    materialData: "double_plant"
    displayName: "&1Napraforgó"
  '26':
    materialData: "feather"
    displayName: "&1Toll"
  '27':
    materialData: "GOLD_CHESTPLATE"
    displayName: "&1Arany mellvért"
    lore:
    - ""
    - "Különleges!"
  '28':
    materialData: "bookshelf"
    displayName: "&1Könyvespolc"
    lore:
    - ""
    - "Olvasd el az összes könyvet, építs egy rakétát"
    - "   és repülj el a holdra ;)"
  '29':
    materialData: "cactus"
    displayName: "&1Kaktusz"
  '30':
    materialData: "hay_block"
    displayName: "&1Szalmabála"
  '31':
    materialData: "iron_sword"
    displayName: "&1Kard"
    lore:
    - ""
    - "Egyszerű vaskard."
    - "Kicsit unalmas..."


