usemySQL: false
mySQLconn: jdbc:mysql://localhost:3306/minecraft
mySQLuname: root
mySQLpass: password
globalUseEconomy: true
allowWorldTeleport: true
defaultWEAnywhere: false
NbClearSpools: 3
NbBlocksPerClearStep: 50000
AdvancedLogging: false
worlds:
  plotworld:
    PlotAutoLimit: 1000
    DaysToExpiration: 31
    ProtectedBlocks:
    - 54
    - 61
    - 62
    - 94
    - 93
    - 84
    - 25
    - 118
    - 117
    - 138
    - 140
    - 149
    - 150
    - 154
    - 158
    - 23
    - 64
    - 71
    - 107
    - 96
    - 122
    - 69
    - 77
    - 143
    - 197
    - 196
    - 195
    - 194
    - 193
    - 183
    - 184
    - 185
    - 186
    - 187
    - 92
    - 146
    - 151
    - 178
    - 155
    - 120
    - 145
    - 219
    - 220
    - 221
    - 222
    - 223
    - 224
    - 225
    - 226
    - 227
    - 228
    - 229
    - 230
    - 231
    - 232
    - 233
    - 234
    PreventedItems:
    - '328'
    - '343'
    - '342'
    - '333'
    - '407'
    - '408'
    - '422'
    - '416'
    - '444'
    - '445'
    - '446'
    - '447'
    - '448'
    - '426'
    economy:
      UseEconomy: true
      CanPutOnSale: true
      RefundClaimPriceOnReset: false
      RefundClaimPriceOnSetOwner: false
      ClaimPrice: 500.0
      ClearPrice: 0.0
      AddPlayerPrice: 0.0
      DenyPlayerPrice: 0.0
      RemovePlayerPrice: 0.0
      UndenyPlayerPrice: 0.0
      PlotHomePrice: 0.0
      SellToPlayerPrice: 250.0
      BiomeChangePrice: 0.0
      ProtectPrice: 0.0
      DisposePrice: 1000.0
    AutoLinkPlots: true
    DisableExplosion: true
    DisableIgnition: false
    UseProgressiveClear: false
    Projectiles: true
