# 
# Your database information should go here.# 
SQLite: true
sql:
  host: 127.0.0.1
  port: '3306'
  database: database
  user: user
  pass: password
auction:
  listingPrice: 0
  listingHours: 48
  unclaimedHours: 240
  preventCreativeSale: true
  maxSellPrice: 1000000000000
  taxPercentage: 0.0
  maxPermissionIncludeExpired: false
blacklist:
- 38:81
- '7'
- '166'
- '422'
- '137'
- '255'
- '210'
- '210'
- '217'
blacklistLore:
- mcMMO Ability Tool
language:
  mainMenuName: Aukciós Ház
  currentListingsMenuName: Jelenlegi tételeid
  expiredMenuName: '&6Lejárt tételek'
  purchaseItemMenuName: 'Tétel megvétele: Biztos vagy benne?'
  menuItemText:
    listedItem:
      lore:
      - '&7-------------------------'
      - '&aKatt ide a vételhez.'
      - ''
      - '&9Ár: &e$%price%'
      - '&9Eladó: &e%seller%'
      - '&9Lejár: &e%time%'
      - '&7-------------------------'
    yourListedItem:
      lore:
      - '&7-------------------------'
      - '&cKatt ide a megszakításhoz.'
      - ''
      - '&9Ár: &e$%price%'
      - '&9Lejár: &e%time%'
      - '&7-------------------------'
    yourExpiredItem:
      lore:
      - '&7-------------------------'
      - '&aKatt ide, hogy visszaszerezd.'
      - '&7-------------------------'
    yourListedItems:
      id: '264'
      name: '&6Összes eladni kívánt tételed'
      lore:
      - '&aIde kattintva megtekintheted'
      - '&aa jelenlegi eladni kívánt áruidat.'
      - ''
      - '&9Eladó: &e%selling%'
    yourExpiredItems:
      id: '394'
      name: '&6Lejárt Tételek / Megszakított tételek'
      lore:
      - '&aKattints ide, hogy a megszakított'
      - '&aés lejárt tételedet megtekintsd.'
      - ''
      - '&9Visszakérhető tárgyak: &e%expired%'
    returnAllItems:
      id: '390'
      name: '&6Mindent visszavon'
      lore:
      - '&aKatt ide hogy a meglévő és lejárt'
      - '&atételedet vissza szerezd.'
    previousPage:
      id: '339'
      name: '&6Előző oldal'
    refreshPage:
      id: '175'
      name: '&6Oldal frissítése'
    nextPage:
      id: '339'
      name: '&6Következő oldal'
    backButton:
      id: '339'
      name: '&6Vissza'
    howToSell:
      id: '388'
      name: '&6Hogy adj el egy tárgyat/blokkot'
      lore:
      - '&aAhhoz, hogy feltegyél az aukcióra egy árut, fogj egy tételt'
      - '&aa kezedbe, és írd be a következőt: &b/ah sell <ár>&a.'
    mainWhatIsThisPage:
      id: '340'
      name: '&6Mi ez az oldal?'
      lore:
      - '&aJelenleg az aukciós házban vagy'
      - '&aitt tudsz venni árukat, és el is'
      - '&atudod adni a sajátjaidat.'
      - ''
      - '&aAz aukciós ház tökéletes arra, hogy'
      - '&apénzt szerezz a felesleges cuccaidból'
      - '&aamiket meguntál.'
    yourListedWhatIsThisPage:
      id: '340'
      name: '&6Mi ez az oldal?'
      lore:
      - '&aItt vannak a saját tételeid, melyeket'
      - '&afeltettél az aukcióra, hogy megvegyék'
      - '&atőled a játékosok.'
      - ''
      - '&aMegtudod nézni itt az áruidat, vagy'
      - '&avisszakérni a lejárt tételeidet.'
    expiredWhatIsThisPage:
      id: '340'
      name: '&6Mi ez az oldal?'
      lore:
      - '&aEz az oldal tartalmazza az összes lejárt,'
      - '&amegszakított, vagy visszakért árud listáját'
      - ''
      - '&aCsak kattints az árudra, ha van elég hely'
      - '&aaz eszköztáradban, és visszakapod tételeidet.'
    purchaseConfirm:
      name: '&aElfogadás'
    purchaseCancel:
      name: '&cMegszakítás'
    purchaseItem:
      lore:
      - ''
      - '&9Ár: &e$%price%'
      - '&9Eladó: &e%seller%'
    recentSalesLog:
      id: '266'
      name: '&6Legutóbb eladott tárgyak'
      logLineFormat: '&9Eladva &e%item% &9neki &e%buyer% &9ennyiért &e$%price%&9.'
      noneSoldLore: '&cMég nincs eladott tárgyad.'
  clickFails:
    clickFailItem: '152'
    notEnoughInventory: Nincs elég hely a táskádban
    cannotPurchaseSelf: A saját árudat nem tudod megvenni
    notExists: Ez a tétel már nem elérhető
    cannotAfford: Ez nem engedélyezett
    noListingsToReturn: Ezt a tételt már nem lehet visszavenni
  chatMessages:
    itemPurchased: '&eTétel &6Eladva&e!'
    buyerPurchased: '&6%buyer% &emegvette az egyik tételedet, így kaptál: &6$%taxedPrice%&e!'
    listedItem: '&eFelraktál &6egy árut &eaz &6Aukciós Házba&e!'
    listingCancel: '&eKivettél &6egy tételt &eaz aukcióról. A lejárt vagy visszakért
      tételedet megtekintheted itt, &6/ah expired&e.'
    adminRemoveListing: '&eTétel eltávolítva.'
    expiredReturned: '&eEgy tétel &6visszakerült &eaz eszköztáradba.'
    notEnoughInventory: '&cNincs elég hely az eszköztáradban.'
    returnedAll: '&6Minden &elejárt tételed &6visszakerült&e.'
    unknownCommand: '&cIsmeretlen parancs. Használd ezt: &d/ah help'
    notHoldingItem: '&cNincs a kezedben semmi áru.'
    inCreative: '&cKreatívban nem lehet eladni árut.'
    noMore: '&cNem tudsz listázni több tételt'
    max: '&cEgyszerre 45 tárgynál nem lehet több tételt listázni.'
    invalidPrice: '&cEz nem valódi ár.'
    maxMoney: '&6Maximálisan &c$999,999,999 &6értékben lehet felrakni árut'
    maxSetMoney: '&6Nem tudsz &c$1,000,000,000,000 &6érték fölött eladni árut'
    notEnoughMoney: '&cNincs elég pénzed ahhoz, hogy listára kerüljön az aukciód.'
    getHelp: '&cHasználd a /ah help parancsot a segítségért.'
    isBlacklisted: '&cEz az áru feketelistán szerepel, nem lehet eladni!'
    help:
    - '&9/ah - &6A aukciós Ház megnyitása.'
    - '&9/ah sell <amount>- &6A kezedben lévő áru eladása.'
    - '&9/ah selling - &6Az eladásra rakott tételeid böngészése.'
    - '&9/ah expired - &6A lejárt tételeid böngészése.'
