# ----------------------------------------------------------------------------#
#                                                                             #
#                              Connect4 config                                #
#                                                                             #
#                                  by Nikl                                    #
# ----------------------------------------------------------------------------#

# name of the language file (in the folder 'language')
langFile: "lang_hu.yml"

gameBox:
  mainButton:
    # define the Material and data for the button (format: 'material:data')
    materialData: "22"
    # display name of the button
    displayName: "&3ConnectFour"
    # lore of the button
    lore:
    - ""
    - "&1Gyüjts ki 4-et egy sorba ;)"
  gameButtons:
    easy:
      materialData: "22"
      displayName: "&aKiképzés"
      lore:
      - ""
      - "&1Ára: &45"
      - "&1Jutalom: &a7"
      slot: 20
      cost: 5
      reward: 7
      # optional custom time per move in seconds (default is 30)
      timePerMove: 20
      # optional custom min number of chips before any winnings are payed (default: 7)
      #     if the game is quited earlier by closing it, the player left int he game will not get payed the winnings, but will get back any money he payed to play the game.
      # set it to a negative number to turn this off
      minNumberOfPlayedChips: 7
      inviteGuiTitle: "  &3ConnectFour &rkiképzés elindítása"
    saveStats:
      materialData: "gold_block"
      displayName: "&c&lVerseny"
      lore:
      - ""
      - "&cKerülj fel a &ltop listára"
      - "&aSok Szerencsét"
      - ""
      - "&1CÁra: &450"
      - "&1Jutalom:: &a75"
      - "&1Zseton: &a1"
      slot: 24
      cost: 50
      reward: 75
      # if true the best score of this button is saved
      saveStats: true
      tokens: 1
      inviteGuiTitle: "     Kezdjük a  &cVersenyt"
  topListButtons:
    # use the same key as the game you want to display the top list for
    #   for that button 'saveStats' must be true (see above)
    saveStats:
      materialData: "gold_block"
      displayName: "&c&lTop lista"
      lore:
      - ""
      - "&cCompetition &1top list"
      slot: 33
      # inventory title of the top list (%player% and %game%)
      inventoryTitle: '              Top Lista'
      # Lore of the skulls in the inventory. Use %rank% for the rank and %time% for the time in 'mm:ss'
      skullLore:
      - ''
      - '&6Rank:&1 %rank%'
      - '&6Gyözelmek:&1 %wins%'


rules:
  # enable/disable sound
  playSounds: true


# requires vault and an economy plugin
#   to enable economy do not forget to enable it for GameBox too
economy:
  enabled: false

# add as many as you want
#   the players chips are selected randomly
chips:
  enzy:
    materialData: "340"
    displayName: "&3%player% játékos Ismerettára"
    # optional lore
    lore:
    - ""
    - "&cElég nehéz..."
  sparks:
    materialData: "377"
    displayName: "&3%player% játékos Szikrája"
  dia:
    materialData: "diamond"
    displayName: "&3%player% játékos Kincse"
  apple:
    materialData: "apple"
    displayName: "&3%player% játékos almája"
  emerald:
    materialData: "388"
    displayName: "&3%player% játékos Drágaköve"
  crystal:
    materialData: "406"
    displayName: "&3%player% játékos Kristálya"
