# ----------------------------------------------------------------------------#
#                                                                             #
#                              Connect4 config                                #
#                                                                             #
#                                  by Nikl                                    #
# ----------------------------------------------------------------------------#

# Name of the language file (in the folder 'language/connectfour')
# Please use the full name, including the file ending (.yml)
langFile: "lang_hu.yml"

gameBox:
  mainButton:
    # define the Material and data for the button (format: 'material:data')
    materialData: "lapis_block"
    # display name of the button
    displayName: "&3Amőba"
    # lore of the button
    lore:
    - ""
    - "&1Gyüjts ki 4-et egy sorba ;)"
  gameButtons:
    easy:
      materialData: "lapis_block"
      displayName: "&aKiképzés"
      lore:
      - ""
      - "&1Ára: &45"
      - "&1Jutalom: &a7"
      slot: 20
      cost: 5
      reward: 7
      # optional custom time per move in seconds (default is 30)
      timePerMove: 20
      # optional custom min number of chips before any winnings are payed (default: 7)
      # this only effects payouts when one player quits/gives up
      minNumberOfPlayedChips: 7
      inviteGuiTitle: "&3ConnectFour &rkiképzés elindítása"
    saveStats:
      materialData: "gold_block"
      displayName: "&c&lVerseny"
      lore:
      - ""
      - "&cKerülj fel a &ltoplistára"
      - "&aSok Szerencsét"
      - ""
      - "&1CÁra: &450"
      - "&1Jutalom: &a75"
      - "&1Zseton: &a1"
      slot: 24
      cost: 50
      reward: 75
      # if true the best score of this button is saved
      saveStats: true
      tokens: 1
      inviteGuiTitle: "     Kezdjük a  &cVersenyt"
  topListButtons:
    # use the same key as the game you want to display the top list for
    #   for that button 'saveStats' must be true (see above)
    saveStats:
      materialData: "gold_block"
      displayName: "&c&lTop lista"
      lore:
      - ""
      - "&cVerseny &1toplista"
      slot: 33
      # inventory title of the top list (%player% and %game%)
      inventoryTitle: '              Toplista'
      # Lore of the skulls in the inventory. Use %rank% for the rank and %time% for the time in 'mm:ss'
      skullLore:
      - ''
      - '&6Helyezés:&1 %rank%'
      - '&6Gyözelmek:&1 %wins%'


rules:
  # enable/disable sound
  playSounds: true


# requires vault and an economy plugin
#   to enable economy do not forget to enable it for GameBox too
economy:
  enabled: false

# add as many as you want
#   the players chips are selected randomly
chips:
  enzy:
    materialData: "book"
    displayName: "&3%player% játékos Ismerettára"
    # optional lore
    lore:
    - ""
    - "&cElég nehéz..."
  sparks:
    materialData: "blaze_powder"
    displayName: "&3%player% játékos Szikrája"
  dia:
    materialData: "diamond"
    displayName: "&3%player% játékos Kincse"
  apple:
    materialData: "apple"
    displayName: "&3%player% játékos almája"
  emerald:
    materialData: "388"
    displayName: "&3%player% játékos Drágaköve"
  crystal:
    materialData: "406"
    displayName: "&3%player% játékos Kristálya"
